### ISSUE TITLE
Video Downloaded not playing 

### ISSUE THREAD

**Issue by Abhilashken** [maleimings/ExoPlayerOfflineDemo#1]
I have tried running your code. 
Downloaded the video TestCaseUHD/2b/11/MultiRate.mpd
Downloaded completed.
Navigated to the download folder, shows the above-downloaded video in the list.

Tried playing that video, "Video not playing".

Is this code still working or some logical issue I am missing, Kindly explain.

**Comment by maleimings** [comment]
Did you try other videos? it works for me.
